### ISSUE TITLE
Getting error when saving some files

### ISSUE THREAD

**Issue by donaldrivard** [joeferraro/MavensMate-Atom#237]
OSX 10.10.5
Atom 1.0.7

Getting the following error when saving some files. Not all some files save fine:

"result": "Could not compile metadata",
  "error": "An unexpected error occurred. Please include this ErrorId if you contact support: 129906996-16006 (1754791447)",
  "stack": "UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 129906996-16006 (1754791447)\n  at [object Object].HttpApi.getError (/Users/drivard/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:240:13)\n  at /Users/drivard/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:85:22\n  at /Users/drivard/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/lib/core.js:33:15\n  at flush (/Users/drivard/.atom/packages/MavensMate-Atom/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)\n  at process._tickCallback (node.js:357:13)\n",
  "promiseId": "ce258b30-4ad3-11e5-93d3-f94827827489"
}

**Comment by joeyguacamole** [comment]
I was experiencing the exact same issue under Atom 1.0.19 just yesterday.
Now it works again, however, without having changed anything (connection, setup etc.)
Possibly just a temporary Salesforce server error?
What instance were you on, @donaldrivard ?

**Comment by dsharrison** [comment]
Yes, a stack trace that includes the ErrorId in that format is an internal server error from Salesforce. While this could be caused by an IDE I have usually found it was just a bug in Salesforce's error handling (meaning I had an error in my code, but rather than the compiler catching it and returning an error message, it was crashing).

**Comment by joeferraro** [comment]
I run into this from time to time as well. This is likely a salesforce server-side issue. Unless we can find some MavensMate-specific behavior that causes this, I'm not sure there's much we can do.

**Comment by dsharrison** [comment]
I don't know if this is enough information to mark this as not an issue, but I can confirm that when I have gotten this in MavensMate I have gotten the same error in a javascript alert by going into the Developer Console and attempting to save the same code.

**Comment by joeferraro** [comment]
interesting. thanks for the additional information, @dsharrison. I'm going to mark as closed for now.

**Comment by joralbert** [comment]
OS: Win 7 x64
Atom: 1.3.3
Mavensmate: 0.0.10

Hi peop0le, since 1 or 2 weeks, I`ve been having this iddue with some files, when tryng to save from Atom into SF. This occurs with some Apex class files (only some of them).

"id": "566aed30-d974-11e5-a751-9d90f9dedf60",
  "complete": true,
  "operation": "compile-metadata",
  "error": "An unexpected error occurred. Please include this ErrorId if you contact support: 454887273-26513 (-516763223)",
  "stack": "UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 454887273-26513 (-516763223)\n    at HttpApi.getError (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\jsforce\\lib\\http-api.js:240:13)\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\jsforce\\lib\\http-api.js:85:22\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\promise\\lib\\core.js:33:15\n    at flush (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\asap\\asap.js:27:13)\n    at doNTCallback0 (node.js:416:9)\n    at process._tickCallback (node.js:345:13)",
  "promiseId": "562d47f0-d974-11e5-9e4f-b5157e5b096e"
