### ISSUE TITLE
re-implement vf live preview

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate-Atom#249]

**Comment by viraj89** [comment]
I'm used to using Sublime, but after [this](https://www.youtube.com/watch?v=FiFjPxhUyVY) video of yours, I thought to give a try using Atom, due to quite obvious reason of live preview. 

Currently does it only support Mac? Or supports even on Windows? 

At my end, it didn't work. Pls help/suggest as its really cool feature to be used while working on VF pages. 

Pls re-implement for Windows users. 

![atom](https://cloud.githubusercontent.com/assets/9387490/14432500/12bb24f8-0028-11e6-8a63-2b1a80b30e51.jpg)
