### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by Saul3d** [joeferraro/MavensMate-Atom#268]
Platfomr: Mac OS X 10.10.5
MavensMate:1.0.3
Atom:1.0.15
Do not see the global settings for set mm_workspace in Mavenmate package setting, in addition none of the menu items under mavensmate is not working.

**Comment by joeferraro** [comment]
@Saul3d please update your issue according to the guidelines: https://github.com/joeferraro/MavensMate-Atom/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by force2b** [comment]
Taking a guess on this, but I think I *had* the same issue.

* Platform: Windows 7 32-bit
* MM-Atom Version: 1.03
* MavensMate-App: v0.0.1-win-x86
* Reproduce: Try nearly any MavensMate menu option (Open MavensMate UI, New Project, Open Project, Global Settings, etc.)
* The MavensMate-App executable is running while I'm in Atom (I assume it needs to be, but don't see any docs that say either way)

Error:
```
[September 22nd 2015, 10:44:24 am]
> Opening settings UI
> undefined
{
  "promiseId": "6b23cf80-6138-11e5-826e-3167badcd01f",
  "error": {}
}
```

It appears the error was solved by going to Settings in the MavensMate-App (not Atom) and adding a path to the Workspace. I would have expected that to be filled in already since I had an earlier version of MM-Atom installed, but it was blank. Once I added that and restarted Atom, all the MM menu options started to work again.

**Comment by AccentureDavin** [comment]
@force2b could you expand on what you mean by 'Settings in the MavensMate-App (not Atom)' please?

When I try MavensMate -> Settings -> Global / Plugin Setting nothing happens, which is consistent with the behaviour reported in this issue by yourself & @Saul3d

**Comment by force2b** [comment]
@AccentureDavin I mean that you have to click on Settings under the hamburger menu in the MavensMate-App app (a bit redundant there). This new app is where all settings are. In my case, I couldn't access those settings from Sublime/Atom until I fixed the settings (adding the workspace) in the MavensMate-App app.

**Comment by AccentureDavin** [comment]
@force2b I see, thanks. I wasn't aware of that app. 

Yes, setting the workspace there and leaving the app running in the background appears to fix the problem.

**Comment by lnslevin** [comment]
I don't see setting under the MavensMate app am I missing something.  This is what I see:

<img width="167" alt="screen shot 2015-09-22 at 10 34 29 pm" src="https://cloud.githubusercontent.com/assets/1851709/10036771/290027a6-617a-11e5-9f5f-d3a76ef1ddb9.png">

**Comment by joeferraro** [comment]
Have you installed the latest version of MavensMate-app?

https://github.com/joeferraro/MavensMate-app/releases/latest

Install directions for MavensMate-Atom v1.x can be found here: https://github.com/joeferraro/MavensMate-Atom

**Comment by lnslevin** [comment]
ahh that was it, I was hitting update but it wasn't finding it manually performing the update worked

Thanks!
