### ISSUE TITLE
Error reaching local MavensMate server from MavensMate-Atom

### ISSUE THREAD

**Issue by sbedathur** [joeferraro/MavensMate-Atom#269]
I am trying to create a new Lightning App using MavensMate for Atom plugin (OS X Yosemite 10.10.5). I am using MavensMate App v0.0.2 and MavensMate-Atom plugin version 1.0.3. It appears the plugin is unable to connect to the MavensMate app. If I try to open the project directly from MavensMate app, it keeps trying forever. I can open the project directly from Atom while the App is running.

Here is the console message.
> Opening new Lightning App UI
> Error reaching local MavensMate server
{
  "code": "ECONNRESET",
  "promiseId": "91a2db50-6152-11e5-b090-954639e37125",
  "success": false
}

**Comment by joeferraro** [comment]
Are you behind a firewall?

**Comment by sbedathur** [comment]
No, I am not.

**Comment by volubilis** [comment]
Hello I am getting the same error. Any update?

**Comment by mh2292** [comment]
I'm getting the same issue. This happens when I run mavensmate:compile-file. I get the following error:
> Compiling file.cls
> Error reaching local MavensMate server. Please ensure MavensMate-app (https://github.com/joeferraro/mavnesmate-app) is installed and running.
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 56248,
  "promiseId": "cf9f1d30-67ae-11e5-8eee-b9bef5a07ecd",
  "success": false
}

**Comment by sribedathur** [comment]
I was able to resolve this issue by recreating the project from scratch. I had an existing project and thought I could just continue to work in that project after updating the MavensMate plugin (and installing the MavensMate App). I haven't investigated why that wouldn't work, but the above fix works in both Atom and SublimeText.

**Comment by arpanvpatel** [comment]
I'm getting the same issue. This happens when I run mavensmate:compile-file. I get the following error:

Error reaching local MavensMate server. Please ensure MavensMate-app (https://github.com/joeferraro/mavnesmate-app) is installed and running.
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 56248,
  "promiseId": "599f0150-67c1-11e5-bfe1-37a90aa1717b",
  "success": false
}

**Comment by agentgill** [comment]
I am getting same issue across the board. Also with Sublime Version. Both Marvicks and El Capitan.

**Comment by agentgill** [comment]
Here is my error

[October 1st 2015, 11:30:09 pm]
> Opening new project UI
> Error reaching local MavensMate server. Please ensure MavensMate-app 

(https://github.com/joeferraro/mavnesmate-app) is installed and running.
{
  "code": "ECONNREFUSED",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 56248,
  "promiseId": "f94c7af0-688b-11e5-93dd-bbc037cee7d7",
  "success": false
}

**Comment by agentgill** [comment]
Figured it out so deleted my comment - but you have to install this first

https://github.com/joeferraro/mavensmate-app/releases then you are good

**Comment by joeferraro** [comment]
As the error message indicates, please install MavensMate-app and ensure it is running.

https://github.com/joeferraro/MavensMate-Atom#installation

**Comment by edguz2408** [comment]
@joeferraro What should I do if I'm behind a firewall?
