### ISSUE TITLE
EACCES: permission denied, mkdir '[object Object]'

### ISSUE THREAD

**Issue by manujCLI** [joeferraro/MavensMate-Atom#301]
While creating new project getting this error.
<img width="753" alt="screen shot 2016-03-02 at 3 13 35 pm" src="https://cloud.githubusercontent.com/assets/8359074/13456526/938d7ff4-e089-11e5-9cc8-2c6b5d4e5188.png">

**Comment by jziesing** [comment]
Curious if you figured out how to get past this? seems like i need to change permissions for Mavens mate or a particular folder.  Let me know if you have any ideas

**Comment by jziesing** [comment]
nevermind, make sure the workspace is accessable

[
    "/Users/user/Documents/mavensmate"
]

**Comment by iDev0urer** [comment]
@manujCLI It looks like you entered an object into the workspace parameters instead of an array. Make sure your workspaces look like the code above posed by @jziesing and not this:
```
{  "/Users/user/Documents/mavensmate" }
```

also if you are on Windows you should be doing double backslashes like this `C:\\Users\\username\\Documents\\projects`
